//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MapEditor.rc
//
#define ID_FILEEDIT_CAR                 0
#define IDC_OBJECT_ADD_BUTTON           3
#define IDC_EDITFILE_LOAD               3
#define IDC_OBJECT_SAVE_BUTTON          4
#define IDC_EDITFILE_SAVE               4
#define IDD_EDITFILE_DIALOG             9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_MapEditorTYPE               129
#define ID_ERROR_MAP_OPEN               129
#define IDB_BITMAP1                     130
#define IDB_LEFTARROW                   130
#define ID_ERROR_TERRAIN_OPEN           130
#define IDD_NEW_DIALOG                  131
#define IDD_NEW_FILE                    131
#define ID_CONFIRM_REPLACE              131
#define ID_ERROR_TERRAIN_SAVE           132
#define ID_ERROR_MAP_SAVE               133
#define ID_ERROR_STARTPOS               134
#define IDR_TREE_MENU                   135
#define ID_ERROR_PATH                   135
#define IDD_OBJECTPROPERTIESDIALOG      137
#define IDD_DIALOG1                     138
#define IDD_FILE_OPEN_DIALOG            138
#define IDD_FILE_SAVE_DIALOG            139
#define IDR_DIR_ICON                    140
#define IDR_FILE_ICON                   141
#define IDB_LEFTARROW_UP                143
#define IDB_LEFTARROW_DOWN              144
#define IDB_RIGHTARROW_DOWN             148
#define IDD_MAP_PROPERTIES              149
#define IDR_MAINFRAME2                  150
#define IDI_EDIT_FILE_ICON              152
#define IDC_NEW_HEIGHT                  1000
#define IDC_NEW_WIDTH                   1001
#define IDC_SET_LOAD_BUTTON             1007
#define IDC_ICON_LOAD_BUTTON            1008
#define IDC_ROAD_EDIT                   1009
#define IDC_LIGHT_BROWSE_BUTTON         1010
#define IDC_OBJECTS_COMBO               1011
#define IDC_PHYSICS_BROWSE_BUTTON       1012
#define IDC_ROAD_RADIO                  1013
#define IDC_OBJECT_RADIO                1014
#define IDC_OBJECT_NAME_EDIT            1015
#define IDC_ROAD_TEXTURE_LIST           1016
#define IDC_TEXTURE_ADD_BUTTON          1017
#define IDC_TEXTURE_DELETE_BUTTON       1018
#define IDC_ROAD_TEXTURE_UP             1019
#define IDC_TEXTURE_RENAME_BUTTON       1020
#define IDC_ROAD_TEXTURE_DOWN           1021
#define IDC_OBJECT_SIZEX_EDIT           1022
#define IDC_SET_NAME_EDIT               1023
#define IDC_LIGHT_NAME_EDIT             1024
#define IDC_PHYSICS_NAME_EDIT           1025
#define IDC_MODEL_NAME_EDIT             1026
#define IDC_PHYSICS_EDIT_BUTTON         1027
#define IDC_MODEL_BROWSE_BUTTON         1028
#define IDC_LIGHT_EDIT_BUTTON           1029
#define IDC_SET_BROWSE_BUTTON           1030
#define IDC_SET_ICON_EDIT               1031
#define IDC_ICON_BROWSE_BUTTON2         1032
#define IDC_PROPIMAGE                   1033
#define IDC_FILE_LIST                   1035
#define IDC_SAVE_FILE_NAME              1037
#define IDC_MAP_LOAD_WALLSET            1039
#define IDC_MAP_TEXTURESET              1040
#define IDC_MAP_HOURS                   1041
#define IDC_ROAD_PHTEXTURE_LIST         1042
#define IDC_MAP_MINUTES                 1042
#define IDC_ROAD_PHTEXTURE_UP           1043
#define IDC_MAP_NAME                    1043
#define IDC_ROAD_PHTEXTURE_DOWN         1044
#define IDC_MAP_FOGCOLOR                1044
#define IDC_PHTEXTURE_ADD_BUTTON        1045
#define IDC_MAPP_NAME                   1045
#define IDC_MAP_WALLSET                 1045
#define IDC_PHTEXTURE_RENAME_BUTTON     1046
#define IDC_MAP_LOAD_TEXTURESET         1046
#define IDC_PHTEXTURE_DELETE_BUTTON     1047
#define IDC_MAP_LOAD_GRASS              1047
#define IDC_PHTEXTURE_BROWSE_BUTTON     1048
#define IDC_MAP_GRASS                   1048
#define IDC_TEXTURE_BROWSE_BUTTON       1049
#define IDC_MAP_LOAD_SKYSYSTEM          1049
#define IDC_MAP_SKYSYSTEM               1050
#define IDC_MAP_LOGO                    1051
#define IDC_MAP_LOAD_LOGO               1052
#define IDC_MAP_DESCRIPTION             1053
#define IDC_OBJECT_SIZEY_EDIT           1054
#define IDC_EDITFILE_VIEW               1054
#define IDC_OBJECT_MAIN_POSX_EDIT       1055
#define IDC_EDITFILE_EDIT               1055
#define IDC_OBJECT_MAIN_POSY_EDIT       1056
#define IDC_EDITFILE_SAVEAS             1056
#define IDC_OBJECT_SCALEX_EDIT          1057
#define IDC_EDITFILE_LIST               1057
#define IDC_OBJECT_SCALEY_EDIT          1058
#define IDC_OBJECT_SCALEZ_EDIT          1059
#define IDC_OBJECT_ROTATIONX_EDIT       1060
#define IDC_OBJECT_ROTATIONY_EDIT       1061
#define IDC_OBJECT_ROTATIONZ_EDIT       1062
#define IDC_OBJECT_POSITIONX_EDIT       1063
#define IDC_OBJECT_POSITIONY_EDIT       1064
#define IDC_OBJECT_POSITIONZ_EDIT       1065
#define IDC_NEW_NAME                    1066
#define IDC_MAP_MODLIST                 1067
#define IDC_MAP_ALLMODS                 1068
#define IDC_BUTTON2                     1069
#define IDC_MAP_NOMODS                  1069
#define ID_AHOJJAKJE                    32771
#define ID_AHOJJAKJE_TUK                32772
#define ID_AHOJJAKJE_DALSIAPOD          32773
#define ID_DRUHY                        32774
#define ID_TRETI                        32775
#define ID__TEST                        32776
#define ID_AHOJ_DEBIL                   32778
#define ID_AHOJ                         32779
#define ID_TO_JE_DOBRE                  32780
#define ID_AHOJ_AHOJ                    32781
#define ID_TELE                         32782
#define ID__HALO                        32785
#define ID_Menu                         32786
#define ID_Menu32789                    32789
#define ID_TREE_ADDNEWITEM              32804
#define ID_TREE_CUT                     32806
#define ID_TREE_PASTE                   32807
#define ID_TREE_DELETE                  32808
#define ID_TREE_RENAME                  32809
#define ID_TREE_PROPERTIES              32810
#define ID_TREE_ADDNEWSUBITEM           32811
#define ID_EDIT_TERRAINEDIT             32812
#define ID_EDIT_MAPEDIT                 32814
#define ID_MYFILE_OPEN                  32815
#define ID_MYFILE_SAVE                  32816
#define ID_FILE_LOADTERRAIN             32817
#define ID_FILE_TERRAINOPEN             32818
#define ID_MYFILE_TERRAINOPEN           32819
#define ID_MYFILE_SAVE_AS               32820
#define ID_UNZOOM                       32828
#define ID_ZOOM                         32829
#define ID_MAP_PROPERTIES               32833
#define ID_Menu32834                    32834
#define ID_MAP                          32835
#define ID_EDIT_EDITPATH                32836
#define ID_EDIT_PATHEDIT                32837
#define ID_FILE_EDIT_TEXTURESET         32839
#define ID_FILE_EDIT_CAR                32842
#define ID_FILE_EDIT_LIGHT              32843
#define ID_FILE_EDIT_CURSOR             32844
#define ID_FILE_EDIT_DLGDECL            32846
#define ID_FILE_EDIT_DGDEF              32847
#define ID_FILE_EDIT_SHRUB              32849
#define ID_FILE_EDIT_MODELDEF           32850
#define ID_FILE_EDIT_PHTEXTURE          32851
#define ID_FILE_EDIT_SKYSYSTEM          32852
#define ID_FILE_EDIT_GRASS              32854
#define ID_FILE_EDIT_HELP               32856
#define ID_Menu32869                    32869
#define ID_VIEW_ZOOM                    32870
#define ID_VIEW_UNZOOM                  32871
#define ID_EDIT_EDITLIGHTFILES          32872
#define ID_EDIT_MODELDEFFILES           32873
#define ID_EDIT_PHYSICALTEXTURES        32874
#define ID_EDIT_TEXTURESET              32875
#define ID_EDIT_SKYSYSTEMS              32876
#define ID_EDIT_DIALOGDEFINITIONS       32877
#define ID_EDIT_DIALOGDECLARATIONS      32878
#define ID_EDIT_DIALOGCURSOR            32879
#define ID_EDIT_GRASS                   32880
#define ID_EDIT_SHRUB                   32881
#define ID_EDIT_EDITHELP                32882
#define ID_HELP_USERMANUAL              32885
#define ID_HELP_HELP                    32886
#define ID_ACCELERATOR32888             32888
#define ID_ACCELERATOR32889             32889
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define AFX_IDS_HELPMODEMESSAGE         0xE002
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_WINDOW_SPLIT                 0xE135
#define ID_HELP_INDEX                   0xE142
#define ID_HELP_USING                   0xE144
#define IDB_RIGHTARROW_UP               58112
#define AFX_IDS_SCSIZE                  0xEF00
#define AFX_IDS_SCMOVE                  0xEF01
#define AFX_IDS_SCMINIMIZE              0xEF02
#define AFX_IDS_SCMAXIMIZE              0xEF03
#define AFX_IDS_SCNEXTWINDOW            0xEF04
#define AFX_IDS_SCPREVWINDOW            0xEF05
#define AFX_IDS_SCCLOSE                 0xEF06
#define AFX_IDS_SCRESTORE               0xEF12
#define AFX_IDS_SCTASKLIST              0xEF13
#define AFX_IDS_PREVIEW_CLOSE           0xF005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32890
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
