#ifndef __INCLUDE_WAVEBANK_CAR__
#define __INCLUDE_WAVEBANK_CAR__

typedef enum
{
    XACT_WAVEBANK_CAR_HORN3 = 0,
    XACT_WAVEBANK_CAR_HORN1 = 1,
    XACT_WAVEBANK_CAR_HORN2 = 2,
    XACT_WAVEBANK_CAR_BEEPBEP = 3,
    XACT_WAVEBANK_CAR_CLOP = 4,
    XACT_WAVEBANK_CAR_WINDOWSXPERROR = 5,
    XACT_WAVEBANK_CAR_ATTACK1 = 6,
    XACT_WAVEBANK_CAR_GODLIKE = 7,
    XACT_WAVEBANK_CAR_DOH = 8,
    XACT_WAVEBANK_CAR_DOMINATING = 9,
    XACT_WAVEBANK_CAR_LOSTMATCH = 10,
    XACT_WAVEBANK_CAR_RAMPAGE = 11,
    XACT_WAVEBANK_CAR_SUCKER = 12,
    XACT_WAVEBANK_CAR_UNSTOPPABLE = 13,
    XACT_WAVEBANK_CAR_YEEHAW = 14,
    XACT_WAVEBANK_CAR_YOUSUCK = 15,
    XACT_WAVEBANK_CAR_1 = 16,
    XACT_WAVEBANK_CAR_2 = 17,
    XACT_WAVEBANK_CAR_3 = 18,
    XACT_WAVEBANK_CAR_4 = 19,
    XACT_WAVEBANK_CAR_5 = 20,
    XACT_WAVEBANK_CAR_6 = 21,
    XACT_WAVEBANK_CAR_7 = 22,
    XACT_WAVEBANK_CAR_8 = 23,
    XACT_WAVEBANK_CAR_9 = 24,
    XACT_WAVEBANK_CAR_10 = 25,
    XACT_WAVEBANK_CAR_WINNERCONGRAT = 26,
    XACT_WAVEBANK_CAR_PREPARE = 27,
    XACT_WAVEBANK_CAR_30SEC = 28,
    XACT_WAVEBANK_CAR_1MIN = 29,
    XACT_WAVEBANK_CAR_3MIN = 30,
    XACT_WAVEBANK_CAR_5MIN = 31,
} XACT_WAVEBANK_CAR;

#define XACT_WAVEBANK_CAR_ENTRY_COUNT 32

#endif // __INCLUDE_WAVEBANK_CAR__
