#ifndef __INCLUDE_SOUNDBANK_CAR__
#define __INCLUDE_SOUNDBANK_CAR__

typedef enum
{
    XACT_SOUNDBANK_CAR_CARHORN1 = 0,
    XACT_SOUNDBANK_CAR_CARHORN2 = 1,
    XACT_SOUNDBANK_CAR_CARHORN3 = 2,
    XACT_SOUNDBANK_CAR_MOUSECLICK = 3,
    XACT_SOUNDBANK_CAR_ERROR = 4,
    XACT_SOUNDBANK_CAR_ATTACK = 5,
    XACT_SOUNDBANK_CAR_GODLIKE = 6,
    XACT_SOUNDBANK_CAR_HOMMERDOH = 7,
    XACT_SOUNDBANK_CAR_DOMINATING = 8,
    XACT_SOUNDBANK_CAR_LOSTMATCH = 9,
    XACT_SOUNDBANK_CAR_PREPARE = 10,
    XACT_SOUNDBANK_CAR_WINNERCONGRAT = 11,
    XACT_SOUNDBANK_CAR_YOUSUCK = 12,
    XACT_SOUNDBANK_CAR_YOUHAW = 13,
    XACT_SOUNDBANK_CAR_SUCKER = 14,
    XACT_SOUNDBANK_CAR_UNSTOPABLE = 15,
    XACT_SOUNDBANK_CAR_RAMPAGE = 16,
    XACT_SOUNDBANK_CAR_COUNTDOWN1 = 17,
    XACT_SOUNDBANK_CAR_COUNTDOWN2 = 18,
    XACT_SOUNDBANK_CAR_COUNTDOWN3 = 19,
    XACT_SOUNDBANK_CAR_COUNTDOWN4 = 20,
    XACT_SOUNDBANK_CAR_COUNTDOWN5 = 21,
    XACT_SOUNDBANK_CAR_COUNTDOWN6 = 22,
    XACT_SOUNDBANK_CAR_COUNTDOWN7 = 23,
    XACT_SOUNDBANK_CAR_COUNTDOWN8 = 24,
    XACT_SOUNDBANK_CAR_COUNTDOWN9 = 25,
    XACT_SOUNDBANK_CAR_COUNTDOWN10 = 26,
    XACT_SOUNDBANK_CAR_COUNTDOWN1MIN = 27,
    XACT_SOUNDBANK_CAR_COUNTDOWN30SEC = 28,
    XACT_SOUNDBANK_CAR_COUNTDOWN3MIN = 29,
    XACT_SOUNDBANK_CAR_COUNTDOWN5MIN = 30,
    XACT_SOUNDBANK_CAR_CARHORNRANDOM = 31,
    XACT_SOUNDBANK_CAR_GOAL = 32,
} XACT_SOUNDBANK_CAR;

#define XACT_SOUNDBANK_CAR_CUE_COUNT 33

#endif // __INCLUDE_SOUNDBANK_CAR__
